#!/usr/bin/env node

var apiKeyUtils = require('./../utils/new_api_key_utils');

var entity1Name = process.env.npm_config_entity1;
var entity2Name = process.env.npm_config_entity2;

var runScript = function (callback) {
    apiKeyUtils.createSharedSecret(entity1Name, entity2Name, function (secret) {
        callback(secret)
    });
};

exports.runScript = runScript;

runScript(function (secret) {
    console.log(secret);
    console.log("\n");
    console.log("Secret was saved to: lib/keys/" + entity1Name + "_" + entity2Name + "_secret.json");
    console.log("\n");
    process.exit(0);
});